# Site settings
title: Talks by Maarten Steenhagen
tag_text: Talks
description: Here's a list of past and upcoming talks

# site url
url: http://msteenhagen.github.io/talks

# Build settings
markdown: kramdown

exclude: ["README.md"]
