# Site settings
title: Talks by Maarten Steenhagen
tag_text: Talks
description: Here's a list of past and upcoming talks

# site url
url: http://127.0.0.1:4000

# Build settings
markdown: kramdown

exclude: ["README.md"]
